// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterSourceRequest {
    #[prost(string, tag = "1")]
    pub source_url: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub options: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterSourceResponse {
    #[prost(string, tag = "1")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub tables: ::prost::alloc::vec::Vec<TableInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TableInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub arrow_schema: ::prost::alloc::vec::Vec<u8>,
}
